/* GENERATED by db/appwrite/tools/generate-schema.mjs — do not edit.
 *
 * Columns Postgres filled with DEFAULT now(). Appwrite has no server-side
 * default, so the adapter supplies them on insert instead. See the note in the
 * generator for why events.starts_at is deliberately absent.
 */
export const SERVER_FILLED_TIMESTAMPS: Record<string, string[]> = {
  "categories": [
    "created_at"
  ],
  "communities": [
    "active_since",
    "created_at",
    "updated_at"
  ],
  "profiles": [
    "joined_at",
    "updated_at"
  ],
  "community_members": [
    "joined_at"
  ],
  "listings": [
    "posted_at",
    "updated_at"
  ],
  "requests": [
    "posted_at",
    "updated_at"
  ],
  "events": [
    "created_at",
    "updated_at"
  ],
  "lost_found_reports": [
    "posted_at",
    "updated_at"
  ],
  "saves": [
    "saved_at"
  ],
  "listing_responses": [
    "created_at"
  ],
  "request_offers": [
    "created_at"
  ],
  "event_rsvps": [
    "rsvped_at"
  ],
  "event_saves": [
    "saved_at"
  ],
  "event_forms": [
    "created_at",
    "updated_at"
  ],
  "event_form_responses": [
    "submitted_at"
  ],
  "comments": [
    "created_at",
    "updated_at"
  ],
  "reactions": [
    "created_at"
  ],
  "notifications": [
    "created_at"
  ],
  "alerts": [
    "created_at"
  ],
  "push_subscriptions": [
    "created_at",
    "last_seen_at"
  ],
  "push_queue": [
    "created_at"
  ],
  "saved_searches": [
    "created_at"
  ],
  "conversations": [
    "created_at"
  ],
  "messages": [
    "created_at"
  ],
  "user_blocks": [
    "created_at"
  ],
  "content_reports": [
    "created_at"
  ],
  "moderation_terms": [
    "added_at"
  ],
  "inventory_items": [
    "created_at",
    "updated_at"
  ],
  "impact_log": [
    "created_at"
  ],
  "announcements": [
    "created_at",
    "updated_at"
  ],
  "community_milestones": [
    "reached_at"
  ],
  "sigchi_members": [
    "added_at"
  ],
  "sigchi_claim_attempts": [
    "at"
  ],
  "app_config": [
    "updated_at"
  ],
  "banners": [
    "created_at",
    "updated_at"
  ]
};
