/* GENERATED by db/appwrite/tools/generate-schema.mjs — do not edit.
 * Source: db/appwrite/ownership.json
 */
export const OWNER_COLUMN: Record<string, string> = {
  "profiles": "$id",
  "listings": "user_id",
  "requests": "user_id",
  "events": "created_by",
  "lost_found_reports": "user_id",
  "comments": "user_id",
  "reactions": "user_id",
  "saves": "user_id",
  "alerts": "user_id",
  "notifications": "user_id",
  "saved_searches": "user_id",
  "push_subscriptions": "user_id",
  "event_rsvps": "user_id",
  "event_saves": "user_id",
  "user_blocks": "blocker_id",
  "community_members": "user_id",
  "impact_log": "user_id",
  "inventory_items": "user_id",
  "event_form_responses": "user_id",
  "listing_responses": "user_id",
  "request_offers": "user_id",
  "event_forms": "created_by",
  "content_reports": "reporter_id"
};
export const PRIVATE_TO_OWNER: ReadonlySet<string> = new Set(["saves","alerts","notifications","saved_searches","push_subscriptions","user_blocks","event_form_responses","content_reports"]);
